### ISSUE TITLE
Buildbot error in workerpy at if task.get('platform')

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#172]
```
2019-04-08T15:10:32.494647 state changed to make
2019-04-08T15:10:34.183959 acquired in state makeing
2019-04-08T15:10:34.185438 Traceback (most recent call last):
  File "/seashell/buildbot/buildbot/worker.py", line 126, in work
    yield task
  File "/seashell/buildbot/buildbot/worker.py", line 220, in stage_make
    if task.get('platform'):
AttributeError: 'JobTask' object has no attribute 'get'

2019-04-08T15:10:35.324036 state changed to failed
```

**Comment by rachitnigam** [comment]
Job link?

**Comment by sa2257** [comment]
http://gorgonzola.cs.cornell.edu:8000/jobs/F1Z5p1JEccg.html

**Comment by sa2257** [comment]
Buildbot still fails.
```
2019-04-11T02:43:52.392167 Traceback (most recent call last):
  File "/seashell/buildbot/buildbot/worker.py", line 126, in work
    yield task
  File "/seashell/buildbot/buildbot/worker.py", line 220, in stage_make
    if task.get('platform'):
AttributeError: 'JobTask' object has no attribute 'get'
```

**Comment by sampsyo** [comment]
Huh; I did fix this. Maybe I somehow messed up the deployment? Can you perhaps check whether this is the same thing that I already fixed or a different bug?

**Comment by sa2257** [comment]
Yup, it's fixed. It just wasn't deployed.
